spring.application.name=employees
# MongoDB Configuration
spring.data.mongodb.uri=mongodb+srv://itachi:21savage4LL@learning.cdxgm41.mongodb.net/?appName=learning
spring.data.mongodb.database=employeesdb

server.port=5000
logging.level.org.springframework.data.mongodb=DEBUG